sudo: false
language: ruby
cache: bundler
rvm:
#- 2.1
- 2.1.1

#before_install:
  - openssl aes-256-cbc -K $encrypted_698c8d2aca3b_key -iv $encrypted_698c8d2aca3b_iv -in publish-key.enc -out publish-key -d
install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "m8OFmwvMZ1gRfdYXpMEygPNsIFyYAiAaaaLjdjAlev5uwf5+FAUQN56yLve923s7f8rEHPeeEFIZI+PdM/UJmWwUa1hm+oHLhkckNWQut8HaahRyqARSPhaDCK/rF+SwLLJlkHpIV5vUxlD9IZBEhHYb4P/RzeT3DOKuxTulTKNGa99ptOrGTZLI9pWWF6uPpMHAecFIHNtPsjYkI9Re8ll3uE6pl+fXTtAhxNTrU93LLDO79gIB/15vcXDUSsd0ql9ZCLu1nLCiM2l5Cpyb+HyCNTErRff33tFX0lfmikZRZUmNLc87bl+oxgfZ8GFT5TPZdRATWMzQ/n8zwahHGtXc5I1h/I+QUi3P4lZSTGgKH0XTouY71rq16NCRgXaRqIle1MDERaCxZCH1uMaJOjhRB3iuU4IZrocNffTeQWc7dAPraEeVDQTRQshdPmayRdxhM6xNACbDylsjlsLp05RvIDRRl+5IcYrnXZDz9bNZEDdPW+xs0v88dQ38oQOw960d00TW8S7pO4vKYFd/16sJt54S3IYqxvnb7Y5Vy7I2IpcTzst6uNmZmaT7qhFYh4aIrOYs0oBCZaVxIL6tzxaG17g6WA/ncQCilk4WU5SwQuqFbpdZ0PUVJXSxM/xhS4t4JW8Ru8rp9+ZeMbwx6LTGqyFLbkx1HX5pIB2m580="
branches:
  only:
    - master
